import { RegionData, LanguageCode } from './types';

// Using a stable simplified topology for India
export const INDIA_TOPO_JSON = "https://code.highcharts.com/mapdata/countries/in/custom/in-all-disputed.topo.json";

export const LANGUAGES: { code: LanguageCode; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिंदी (Hindi)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
];

export const GENERIC_DATA: RegionData = {
  id: "GEN",
  name: "region_gen",
  enrolmentRate: 85,
  updateActivity: 45,
  migrationIndex: 0,
  lifecyclePending: 200000,
  population: 50000000,
  lastUpdated: "2023-11-01",
  alerts: ["alert_gen"],
  recommendation: "rec_gen",
  chartData: {
    history: [
      { month: "May", value: 65 },
      { month: "Jun", value: 59 },
      { month: "Jul", value: 80 },
      { month: "Aug", value: 81 },
      { month: "Sep", value: 56 },
      { month: "Oct", value: 55 },
    ],
    demographics: [
      { group: "0-5", value: 15 },
      { group: "5-18", value: 25 },
      { group: "18-40", value: 40 },
      { group: "40+", value: 20 },
    ]
  }
};

export const MOCK_REGIONAL_DATA: Record<string, RegionData> = {
  "National": {
    ...GENERIC_DATA,
    id: "IND",
    name: "region_india_avg",
    enrolmentRate: 92,
    updateActivity: 78,
    migrationIndex: 10,
    lifecyclePending: 12000000,
    population: 1400000000,
    alerts: ["alert_nat_1"],
    recommendation: "rec_nat"
  },
  "Maharashtra": {
    ...GENERIC_DATA,
    id: "MH",
    name: "region_mh",
    enrolmentRate: 96,
    updateActivity: 88,
    migrationIndex: 45,
    lifecyclePending: 850000,
    population: 123000000,
    alerts: ["alert_mh_1", "alert_mh_2"],
    recommendation: "rec_mh",
    chartData: {
      history: [
        { month: "May", value: 70 },
        { month: "Jun", value: 75 },
        { month: "Jul", value: 85 },
        { month: "Aug", value: 90 },
        { month: "Sep", value: 88 },
        { month: "Oct", value: 92 },
      ],
      demographics: [
        { group: "0-5", value: 12 },
        { group: "5-18", value: 20 },
        { group: "18-40", value: 48 },
        { group: "40+", value: 20 },
      ]
    }
  },
  "Uttar Pradesh": {
    ...GENERIC_DATA,
    id: "UP",
    name: "region_up",
    enrolmentRate: 84,
    updateActivity: 60,
    migrationIndex: -20,
    lifecyclePending: 2500000,
    population: 230000000,
    alerts: ["alert_up_1", "alert_up_2"],
    recommendation: "rec_up"
  },
  "Kerala": {
    ...GENERIC_DATA,
    id: "KL",
    name: "region_kl",
    enrolmentRate: 99,
    updateActivity: 40,
    migrationIndex: 5,
    lifecyclePending: 300000,
    population: 35000000,
    alerts: ["alert_kl_1"],
    recommendation: "rec_kl",
    chartData: {
      history: [
        { month: "May", value: 40 },
        { month: "Jun", value: 42 },
        { month: "Jul", value: 45 },
        { month: "Aug", value: 43 },
        { month: "Sep", value: 41 },
        { month: "Oct", value: 40 },
      ],
      demographics: [
        { group: "0-5", value: 8 },
        { group: "5-18", value: 18 },
        { group: "18-40", value: 35 },
        { group: "40+", value: 39 },
      ]
    }
  }
};

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: "ASIAGS",
    app_subtitle: "Aadhaar Societal Intelligence & Adaptive Governance System",
    gov_india: "Government of India",
    satyameva: "Satyameva Jayate",
    login_auth: "Authorized Personnel Only",
    login_userid: "User ID",
    login_password: "Password",
    login_btn: "Secure Login",
    login_warn: "Unauthorized access is a punishable offense under the Aadhaar Act, 2016.",
    role_admin: "Central Admin",
    role_field: "Field Officer",
    role_supervisor: "Data Supervisor",
    sys_op: "System Operational",
    logout: "Logout",
    dash_title: "National Dashboard",
    dash_subtitle: "Select a data layer to visualize societal patterns",
    layer_enrolment: "Enrolment Density",
    layer_updates: "Update Activity",
    layer_migration: "Migration Signals",
    layer_lifecycle: "Lifecycle Gaps",
    map_legend: "Legend",
    map_high: "High Intensity / Saturation",
    map_med: "Medium",
    map_low: "Low / Action Needed",
    panel_pop: "Total Population",
    panel_sat: "Enrolment Saturation",
    panel_analysis: "Societal Intelligence Analysis",
    panel_alerts: "System Alerts",
    panel_rec: "Recommended Governance Action",
    panel_action_btn: "INITIATE ACTION PLAN",
    panel_data_as_of: "Data current as of",
    chart_trend: "6-Month Update Trend",
    chart_demog: "Pending Lifecycle Updates (By Age)",
    fw_welcome: "Welcome back",
    fw_tasks: "Tasks Remaining",
    fw_zone: "Zone",
    fw_new: "New Enrolment",
    fw_verify: "Verify Status",
    fw_assigned: "Assigned Tasks",
    fw_perf: "My Ward Performance",
    fw_cov: "Coverage",
    fw_pending_05: "Pending 0-5",
    fw_assisted: "Assisted",
    footer_rights: "Unique Identification Authority of India. All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_access: "Accessibility",
    footer_disclaimer: "This platform uses anonymized, aggregated metadata only. No Personally Identifiable Information (PII) is processed or displayed on this dashboard.",
    
    // Data Management Portal Keys
    dm_portal_title: "Data Management Gateway",
    dm_portal_subtitle: "Supervised Dataset Ingestion & Monitoring",
    dm_login_link: "Switch to Data Management Portal",
    dm_main_link: "Return to Main Portal",
    dm_total_records: "Total Records Ingested",
    dm_datasets: "Datasets Uploaded",
    dm_last_update: "Last Ingestion",
    dm_upload_title: "Ingest CSV Dataset",
    dm_select_type: "Select Dataset Type",
    dm_drop_file: "Drag and drop CSV file here, or click to browse",
    dm_uploading: "Uploading & Processing...",
    dm_upload_btn: "Upload Dataset",
    dm_audit_log: "Ingestion Audit Log",
    dm_status_success: "Success",
    dm_status_processing: "Processing",
    dm_status_failed: "Failed",
    
    // Region Names (Mocked)
    region_india_avg: "India (National Average)",
    region_mh: "Maharashtra",
    region_up: "Uttar Pradesh",
    region_kl: "Kerala",
    region_gen: "Region",

    // Region Names (Generic / All States)
    region_andhra_pradesh: "Andhra Pradesh",
    region_arunachal_pradesh: "Arunachal Pradesh",
    region_assam: "Assam",
    region_bihar: "Bihar",
    region_chhattisgarh: "Chhattisgarh",
    region_goa: "Goa",
    region_gujarat: "Gujarat",
    region_haryana: "Haryana",
    region_himachal_pradesh: "Himachal Pradesh",
    region_jammu_and_kashmir: "Jammu and Kashmir",
    region_jharkhand: "Jharkhand",
    region_karnataka: "Karnataka",
    region_kerala: "Kerala",
    region_madhya_pradesh: "Madhya Pradesh",
    region_maharashtra: "Maharashtra",
    region_manipur: "Manipur",
    region_meghalaya: "Meghalaya",
    region_mizoram: "Mizoram",
    region_nagaland: "Nagaland",
    region_odisha: "Odisha",
    region_punjab: "Punjab",
    region_rajasthan: "Rajasthan",
    region_sikkim: "Sikkim",
    region_tamil_nadu: "Tamil Nadu",
    region_telangana: "Telangana",
    region_tripura: "Tripura",
    region_uttar_pradesh: "Uttar Pradesh",
    region_uttarakhand: "Uttarakhand",
    region_west_bengal: "West Bengal",
    
    // UTs and Variations
    region_andaman_and_nicobar_islands: "Andaman and Nicobar Islands",
    region_andaman_and_nicobar: "Andaman and Nicobar Islands",
    region_chandigarh: "Chandigarh",
    region_dadra_and_nagar_haveli_and_daman_and_diu: "Dadra and Nagar Haveli",
    region_dadra_and_nagar_haveli: "Dadra and Nagar Haveli",
    region_daman_and_diu: "Daman and Diu",
    region_delhi: "Delhi",
    region_nct_of_delhi: "Delhi",
    region_ladakh: "Ladakh",
    region_lakshadweep: "Lakshadweep",
    region_puducherry: "Puducherry",

    // Data Content Keys
    alert_nat_1: "Mandatory biometric updates lagging in rural sectors",
    rec_nat: "Increase awareness campaigns for 5-15 year age bracket updates.",
    alert_mh_1: "High migration influx detected in Pune/Mumbai corridor",
    alert_mh_2: "Address update surge",
    rec_mh: "Deploy additional update kiosks in industrial zones to handle migration-led address changes.",
    alert_up_1: "Low saturation in districts bordering Nepal",
    alert_up_2: "0-5 Enrolment gap",
    rec_up: "Initiate Anganwadi-level enrolment camps for newborns and infants.",
    alert_kl_1: "Elderly population biometric mismatch increasing",
    rec_kl: "Focus on assisted home-visit updates for geriatric population.",
    alert_gen: "Routine monitoring active",
    alert_gen_min: "Minor anomalies detected",
    rec_gen: "Maintain current service levels.",
    rec_gen_mob: "Deployment of mobile update units recommended.",

    // Insight Narrative Keys
    insight_mig_influx: "Migration data indicates a net influx of population. Address update patterns suggest movement is primarily driven by industrial labor demand.",
    insight_mig_outflow: "Migration data indicates a net outflow of population. Address update patterns suggest movement is primarily driven by seasonal agricultural shifts.",
    insight_life_lag: "Mandatory biometric updates are critically lagging. There is a significant gap in the 5-15 year demographic requiring immediate biometric refresh.",
    insight_life_stable: "Mandatory biometric updates are stable. There is a significant gap in the 5-15 year demographic requiring immediate biometric refresh.",
    insight_activity_high: "Regional activity shows high engagement with Aadhaar services. Population coverage estimates align with projected census data.",
    insight_activity_mod: "Regional activity shows moderate engagement with Aadhaar services. Population coverage estimates align with projected census data."
  },
  hi: {
    app_title: "ASIAGS",
    app_subtitle: "आधार सामाजिक बुद्धिमत्ता और अनुकूलनशील शासन प्रणाली",
    gov_india: "भारत सरकार",
    satyameva: "सत्यमेव जयते",
    login_auth: "केवल अधिकृत कार्मिक",
    login_userid: "उपयोगकर्ता आईडी",
    login_password: "पासवर्ड",
    login_btn: "सुरक्षित लॉगिन",
    login_warn: "अनधिकृत पहुंच आधार अधिनियम, 2016 के तहत एक दंडनीय अपराध है।",
    role_admin: "केंद्रीय प्रशासक",
    role_field: "क्षेत्रीय अधिकारी",
    role_supervisor: "डेटा पर्यवेक्षक",
    sys_op: "सिस्टम चालू है",
    logout: "लॉग आउट",
    dash_title: "राष्ट्रीय डैशबोर्ड",
    dash_subtitle: "सामाजिक पैटर्न देखने के लिए डेटा परत चुनें",
    layer_enrolment: "नामांकन घनत्व",
    layer_updates: "अपडेट गतिविधि",
    layer_migration: "प्रवास संकेत",
    layer_lifecycle: "जीवनचक्र अंतराल",
    map_legend: "संकेत",
    map_high: "उच्च तीव्रता / संतृप्ति",
    map_med: "मध्यम",
    map_low: "कम / कार्रवाई आवश्यक",
    panel_pop: "कुल जनसंख्या",
    panel_sat: "नामांकन संतृप्ति",
    panel_analysis: "सामाजिक खुफिया विश्लेषण",
    panel_alerts: "सिस्टम अलर्ट",
    panel_rec: "अनुशंसित शासन कार्रवाई",
    panel_action_btn: "कार्य योजना शुरू करें",
    panel_data_as_of: "डेटा अद्यतन तिथि",
    chart_trend: "6-महीने का अपडेट रुझान",
    chart_demog: "लंबित जीवनचक्र अपडेट (आयु अनुसार)",
    fw_welcome: "वापसी पर स्वागत है",
    fw_tasks: "शेष कार्य",
    fw_zone: "क्षेत्र",
    fw_new: "नया नामांकन",
    fw_verify: "स्थिति जांचें",
    fw_assigned: "असाइन किए गए कार्य",
    fw_perf: "मेरा वार्ड प्रदर्शन",
    fw_cov: "कवरेज",
    fw_pending_05: "लंबित 0-5",
    fw_assisted: "सहायता प्राप्त",
    footer_rights: "भारतीय विशिष्ट पहचान प्राधिकरण। सर्वाधिकार सुरक्षित।",
    footer_privacy: "गोपनीयता नीति",
    footer_terms: "सेवा की शर्तें",
    footer_access: "सुगम्यता",
    footer_disclaimer: "यह प्लेटफ़ॉर्म केवल अज्ञात, एकत्रित मेटाडेटा का उपयोग करता है। इस डैशबोर्ड पर कोई व्यक्तिगत पहचान योग्य जानकारी (PII) संसाधित या प्रदर्शित नहीं की जाती है।",
    
    dm_portal_title: "डेटा प्रबंधन गेटवे",
    dm_portal_subtitle: "पर्यवेक्षित डेटासेट अंतर्ग्रहण और निगरानी",
    dm_login_link: "डेटा प्रबंधन पोर्टल पर जाएं",
    dm_main_link: "मुख्य पोर्टल पर लौटें",
    dm_total_records: "कुल रिकॉर्ड अंतर्ग्रहण",
    dm_datasets: "अपलोड किए गए डेटासेट",
    dm_last_update: "अंतिम अंतर्ग्रहण",
    dm_upload_title: "CSV डेटासेट अंतर्ग्रहण",
    dm_select_type: "डेटासेट प्रकार चुनें",
    dm_drop_file: "CSV फ़ाइल यहाँ खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें",
    dm_uploading: "अपलोड और प्रोसेसिंग...",
    dm_upload_btn: "डेटासेट अपलोड करें",
    dm_audit_log: "अंतर्ग्रहण ऑडिट लॉग",
    dm_status_success: "सफल",
    dm_status_processing: "प्रक्रिया जारी",
    dm_status_failed: "विफल",

    // Region Names (Mocked)
    region_india_avg: "भारत (राष्ट्रीय औसत)",
    region_mh: "महाराष्ट्र",
    region_up: "उत्तर प्रदेश",
    region_kl: "केरल",
    region_gen: "क्षेत्र",

    // Region Names (Generic / All States)
    region_andhra_pradesh: "आंध्र प्रदेश",
    region_arunachal_pradesh: "अरुणाचल प्रदेश",
    region_assam: "असम",
    region_bihar: "बिहार",
    region_chhattisgarh: "छत्तीसगढ़",
    region_goa: "गोवा",
    region_gujarat: "गुजरात",
    region_haryana: "हरियाणा",
    region_himachal_pradesh: "हिमाचल प्रदेश",
    region_jammu_and_kashmir: "जम्मू और कश्मीर",
    region_jharkhand: "झारखंड",
    region_karnataka: "कर्नाटक",
    region_kerala: "केरल",
    region_madhya_pradesh: "मध्य प्रदेश",
    region_maharashtra: "महाराष्ट्र",
    region_manipur: "मणिपुर",
    region_meghalaya: "मेघालय",
    region_mizoram: "मिजोरम",
    region_nagaland: "नागालैंड",
    region_odisha: "ओडिशा",
    region_punjab: "पंजाब",
    region_rajasthan: "राजस्थान",
    region_sikkim: "सिक्किम",
    region_tamil_nadu: "तमिलनाडु",
    region_telangana: "तेलंगाना",
    region_tripura: "त्रिपुरा",
    region_uttar_pradesh: "उत्तर प्रदेश",
    region_uttarakhand: "उत्तराखंड",
    region_west_bengal: "पश्चिम बंगाल",
    
    // UTs and Variations
    region_andaman_and_nicobar_islands: "अंडमान और निकोबार द्वीप समूह",
    region_andaman_and_nicobar: "अंडमान और निकोबार द्वीप समूह",
    region_chandigarh: "चंडीगढ़",
    region_dadra_and_nagar_haveli_and_daman_and_diu: "दादरा और नगर हवेली",
    region_dadra_and_nagar_haveli: "दादरा और नगर हवेली",
    region_daman_and_diu: "दमन और दीव",
    region_delhi: "दिल्ली",
    region_nct_of_delhi: "दिल्ली",
    region_ladakh: "लद्दाख",
    region_lakshadweep: "लक्षद्वीप",
    region_puducherry: "पुडुचेरी",

    // Data Content Keys
    alert_nat_1: "ग्रामीण क्षेत्रों में अनिवार्य बायोमेट्रिक अपडेट पिछड़ रहे हैं",
    rec_nat: "5-15 वर्ष आयु वर्ग के अपडेट के लिए जागरूकता अभियान बढ़ाएं।",
    alert_mh_1: "पुणे/मुंबई कॉरिडोर में उच्च प्रवासन आमद का पता चला",
    alert_mh_2: "पता अपडेट में वृद्धि",
    rec_mh: "प्रवासन-आधारित पता परिवर्तनों को संभालने के लिए औद्योगिक क्षेत्रों में अतिरिक्त अपडेट कियोस्क तैनात करें।",
    alert_up_1: "नेपाल की सीमा से लगे जिलों में कम संतृप्ति",
    alert_up_2: "0-5 नामांकन अंतर",
    rec_up: "नवजात शिशुओं के लिए आंगनवाड़ी स्तर पर नामांकन शिविर शुरू करें।",
    alert_kl_1: "बुजुर्ग आबादी बायोमेट्रिक बेमेल बढ़ रहा है",
    rec_kl: "वृद्ध आबादी के लिए सहायता प्राप्त गृह-भ्रमण अपडेट पर ध्यान दें।",
    alert_gen: "नियमित निगरानी सक्रिय",
    alert_gen_min: "मामूली विसंगतियों का पता चला",
    rec_gen: "वर्तमान सेवा स्तर बनाए रखें।",
    rec_gen_mob: "मोबाइल अपडेट इकाइयों की तैनाती की सिफारिश की गई।",

    // Insight Narrative Keys
    insight_mig_influx: "प्रवासन डेटा जनसंख्या के शुद्ध आगमन का संकेत देता है। पता अद्यतन पैटर्न बताते हैं कि आंदोलन मुख्य रूप से औद्योगिक श्रम की मांग से प्रेरित है।",
    insight_mig_outflow: "प्रवासन डेटा जनसंख्या के शुद्ध बहिर्वाह का संकेत देता है। पता अद्यतन पैटर्न बताते हैं कि आंदोलन मुख्य रूप से मौसमी कृषि बदलावों से प्रेरित है।",
    insight_life_lag: "अनिवार्य बायोमेट्रिक अपडेट गंभीर रूप से पिछड़ रहे हैं। 5-15 वर्ष की जनसांख्यिकी में तत्काल बायोमेट्रिक रिफ्रेश की आवश्यकता वाला एक महत्वपूर्ण अंतर है।",
    insight_life_stable: "अनिवार्य बायोमेट्रिक अपडेट स्थिर हैं। 5-15 वर्ष की जनसांख्यिकी में तत्काल बायोमेट्रिक रिफ्रेश की आवश्यकता वाला एक महत्वपूर्ण अंतर है।",
    insight_activity_high: "क्षेत्रीय गतिविधि आधार सेवाओं के साथ उच्च जुड़ाव दर्शाती है। जनसंख्या कवरेज अनुमान अनुमानित जनगणना डेटा के साथ संरेखित हैं।",
    insight_activity_mod: "क्षेत्रीय गतिविधि आधार सेवाओं के साथ मध्यम जुड़ाव दर्शाती है। जनसंख्या कवरेज अनुमान अनुमानित जनगणना डेटा के साथ संरेखित हैं।"
  },
  gu: {
    app_title: "ASIAGS",
    app_subtitle: "આધાર સોશ્યલ ઇન્ટેલિજન્સ એન્ડ એડેપ્ટિવ ગવર્નન્સ સિસ્ટમ",
    gov_india: "ભારત સરકાર",
    satyameva: "સત્યમેવ જયતે",
    login_auth: "માત્ર અધિકૃત કર્મચારીઓ",
    login_userid: "યુઝર આઈડી",
    login_password: "પાસવર્ડ",
    login_btn: "સુરક્ષિત લોગિન",
    login_warn: "અનધિકૃત પ્રવેશ આધાર અધિનિયમ, 2016 હેઠળ દંડનીય ગુનો છે.",
    role_admin: "કેન્દ્રીય વ્યવસ્થાપક",
    role_field: "ફીલ્ડ ઓફિસર",
    role_supervisor: "ડેટા સુપરવાઇઝર",
    sys_op: "સિસ્ટમ ચાલુ છે",
    logout: "લોગ આઉટ",
    dash_title: "રાષ્ટ્રીય ડેશબોર્ડ",
    dash_subtitle: "સામાજિક પેટર્ન જોવા માટે ડેટા લેયર પસંદ કરો",
    layer_enrolment: "નોંધણી ગીચતા",
    layer_updates: "અપડેટ પ્રવૃત્તિ",
    layer_migration: "સ્થળાંતર સંકેતો",
    layer_lifecycle: "જીવનચક્ર ગેપ્સ",
    map_legend: "સૂચિ",
    map_high: "ઉચ્ચ તીવ્રતા",
    map_med: "મધ્યમ",
    map_low: "ઓછું / પગલાં જરૂરી",
    panel_pop: "કુલ વસ્તી",
    panel_sat: "નોંધણી સંતૃપ્તિ",
    panel_analysis: "સામાજિક બુદ્ધિ વિશ્લેષણ",
    panel_alerts: "સિસ્ટમ ચેતવણીઓ",
    panel_rec: "ભલામણ કરેલ શાસન પગલાં",
    panel_action_btn: "કાર્ય યોજના શરૂ કરો",
    panel_data_as_of: "ડેટા અપડેટ તારીખ",
    chart_trend: "6-મહિનાનો અપડેટ ટ્રેન્ડ",
    chart_demog: "બાકી જીવનચક્ર અપડેટ્સ (વય મુજબ)",
    fw_welcome: "સ્વાગત છે",
    fw_tasks: "બાકી કાર્યો",
    fw_zone: "ઝોન",
    fw_new: "નવી નોંધણી",
    fw_verify: "સ્થિતિ ચકાસો",
    fw_assigned: "સોંપેલ કાર્યો",
    fw_perf: "મારો વોર્ડ પ્રદર્શન",
    fw_cov: "કવરેજ",
    fw_pending_05: "બાકી 0-5",
    fw_assisted: "સહાયિત",
    footer_rights: "ભારતીય વિશિષ્ટ ઓળખ સત્તામંડળ. સર્વાધિકાર સુરક્ષિત.",
    footer_privacy: "ગોપનીયતા નીતિ",
    footer_terms: "સેવાની શરતો",
    footer_access: "સુલભતા",
    footer_disclaimer: "આ પ્લેટફોર્મ માત્ર અનામી, એકત્રિત મેટાડેટાનો ઉપયોગ કરે છે.",

    dm_portal_title: "ડેટા મેનેજમેન્ટ ગેટવે",
    dm_portal_subtitle: "નિરીક્ષિત ડેટાસેટ ઇન્જેશન અને મોનીટરીંગ",
    dm_login_link: "ડેટા મેનેજમેન્ટ પોર્ટલ પર સ્વિચ કરો",
    dm_main_link: "મુખ્ય પોર્ટલ પર પાછા જાઓ",
    dm_total_records: "કુલ રેકોર્ડ્સ ઇન્જેસ્ટ કરેલા",
    dm_datasets: "અપલોડ કરેલ ડેટાસેટ્સ",
    dm_last_update: "છેલ્લું ઇન્જેશન",
    dm_upload_title: "CSV ડેટાસેટ ઇન્જેશન",
    dm_select_type: "ડેટાસેટ પ્રકાર પસંદ કરો",
    dm_drop_file: "CSV ફાઇલ અહીં ખેંચો અને છોડો, અથવા બ્રાઉઝ કરવા માટે ક્લિક કરો",
    dm_uploading: "અપલોડ અને પ્રોસેસિંગ...",
    dm_upload_btn: "ડેટાસેટ અપલોડ કરો",
    dm_audit_log: "ઇન્જેશન ઓડિટ લોગ",
    dm_status_success: "સફળ",
    dm_status_processing: "પ્રક્રિયા ચાલુ",
    dm_status_failed: "નિષ્ફળ",

    // Region Names
    region_india_avg: "ભારત (રાષ્ટ્રીય સરેરાશ)",
    region_mh: "મહારાષ્ટ્ર",
    region_up: "ઉત્તર પ્રદેશ",
    region_kl: "કેરળ",
    region_gen: "પ્રદેશ",

    // Region Names (Generic / All States)
    region_andhra_pradesh: "આંધ્ર પ્રદેશ",
    region_arunachal_pradesh: "અરુણાચલ પ્રદેશ",
    region_assam: "આસામ",
    region_bihar: "બિહાર",
    region_chhattisgarh: "છત્તીસગઢ",
    region_goa: "ગોવા",
    region_gujarat: "ગુજરાત",
    region_haryana: "હરિયાણા",
    region_himachal_pradesh: "હિમાચલ પ્રદેશ",
    region_jammu_and_kashmir: "જમ્મુ અને કાશ્મીર",
    region_jharkhand: "ઝારખંડ",
    region_karnataka: "કર્ણાટક",
    region_kerala: "કેરળ",
    region_madhya_pradesh: "મધ્ય પ્રદેશ",
    region_maharashtra: "મહારાષ્ટ્ર",
    region_manipur: "મણિપુર",
    region_meghalaya: "મેઘાલય",
    region_mizoram: "મિઝોરમ",
    region_nagaland: "નાગાલેન્ડ",
    region_odisha: "ઓડિશા",
    region_punjab: "પંજાબ",
    region_rajasthan: "રાજસ્થાન",
    region_sikkim: "સિક્કિમ",
    region_tamil_nadu: "તમિલનાડુ",
    region_telangana: "તેલંગાણા",
    region_tripura: "ત્રિપુરા",
    region_uttar_pradesh: "ઉત્તર પ્રદેશ",
    region_uttarakhand: "ઉત્તરાખંડ",
    region_west_bengal: "પશ્ચિમ બંગાળ",
    
    // UTs and Variations
    region_andaman_and_nicobar_islands: "આંદામાન અને નિકોબાર",
    region_andaman_and_nicobar: "આંદામાન અને નિકોબાર",
    region_chandigarh: "ચંદીગઢ",
    region_dadra_and_nagar_haveli_and_daman_and_diu: "દાદરા અને નગર હવેલી",
    region_dadra_and_nagar_haveli: "દાદરા અને નગર હવેલી",
    region_daman_and_diu: "દમણ અને દીવ",
    region_delhi: "દિલ્હી",
    region_nct_of_delhi: "દિલ્હી",
    region_ladakh: "લદ્દાખ",
    region_lakshadweep: "લક્ષદ્વીપ",
    region_puducherry: "પુડુચેરી",

    // Data Content Keys
    alert_nat_1: "ગ્રામીણ વિસ્તારોમાં ફરજિયાત બાયોમેટ્રિક અપડેટ્સ પાછળ છે",
    rec_nat: "5-15 વર્ષની વય જૂથના અપડેટ્સ માટે જાગૃતિ અભિયાન વધારો.",
    alert_mh_1: "પુણે/મુંબઈ કોરિડોરમાં ઉચ્ચ સ્થળાંતર પ્રવાહ મળ્યો",
    alert_mh_2: "સરનામા અપડેટમાં વધારો",
    rec_mh: "સ્થળાંતર-આધારિત સરનામાં ફેરફારોને સંભાળવા ઔદ્યોગિક વિસ્તારોમાં વધારાના અપડેટ કિઓસ્ક મૂકો.",
    alert_up_1: "નેપાળ સરહદના જિલ્લાઓમાં ઓછી સંતૃપ્તિ",
    alert_up_2: "0-5 નોંધણી ગેપ",
    rec_up: "નવજાત શિશુઓ માટે આંગણવાડી સ્તરે નોંધણી કેમ્પ શરૂ કરો.",
    alert_kl_1: "વૃદ્ધ વસ્તી બાયોમેટ્રિક મેળ ખાતું નથી",
    rec_kl: "વૃદ્ધ વસ્તી માટે ઘરે જઈને અપડેટ પર ધ્યાન કેન્દ્રિત કરો.",
    alert_gen: "નિયમિત દેખરેખ સક્રિય",
    alert_gen_min: "નાની વિસંગતતાઓ મળી",
    rec_gen: "વર્તમાન સેવા સ્તર જાળવી રાખો.",
    rec_gen_mob: "મોબાઈલ અપડેટ યુનિટ્સ મૂકવાની ભલામણ.",

    // Insight Narrative Keys
    insight_mig_influx: "સ્થળાંતર ડેટા વસ્તીના ચોખ્ખા પ્રવાહને સૂચવે છે. સરનામાના અપડેટ પેટર્ન સૂચવે છે કે હલનચલન મુખ્યત્વે ઔદ્યોગિક શ્રમની માંગ દ્વારા ચાલે છે.",
    insight_mig_outflow: "સ્થળાંતર ડેટા વસ્તીના ચોખ્ખા જાવકને સૂચવે છે. સરનામાના અપડેટ પેટર્ન સૂચવે છે કે હલનચલન મુખ્યત્વે મોસમી કૃષિ ફેરફારો દ્વારા ચાલે છે.",
    insight_life_lag: "ફરજિયાત બાયોમેટ્રિક અપડેટ્સ ગંભીર રીતે પાછળ છે. 5-15 વર્ષની વસ્તીમાં તાત્કાલિક બાયોમેટ્રિક રિફ્રેશની જરૂર હોય તેવું નોંધપાત્ર અંતર છે.",
    insight_life_stable: "ફરજિયાત બાયોમેટ્રિક અપડેટ્સ સ્થિર છે. 5-15 વર્ષની વસ્તીમાં તાત્કાલિક બાયોમેટ્રિક રિફ્રેશની જરૂર હોય તેવું નોંધપાત્ર અંતર છે.",
    insight_activity_high: "પ્રાદેશિક પ્રવૃત્તિ આધાર સેવાઓ સાથે ઉચ્ચ જોડાણ દર્શાવે છે. વસ્તી કવરેજ અંદાજો અંદાજિત વસ્તી ગણતરીના ડેટા સાથે સંરેખિત છે.",
    insight_activity_mod: "પ્રાદેશિક પ્રવૃત્તિ આધાર સેવાઓ સાથે મધ્યમ જોડાણ દર્શાવે છે. વસ્તી કવરેજ અંદાજો અંદાજિત વસ્તી ગણતરીના ડેટા સાથે સંરેખિત છે."
  },
  bn: {
    app_title: "ASIAGS",
    app_subtitle: "আধার সামাজিক बुद्धিমত্তা এবং অভিযোজিত শাসন ব্যবস্থা",
    gov_india: "ভারত সরকার",
    satyameva: "সত্যমেব জয়তে",
    login_auth: "শুধুমাত্র অনুমোদিত কর্মীদের জন্য",
    login_userid: "ব্যবহারকারী আইডি",
    login_password: "পাসওয়ার্ড",
    login_btn: "সুরক্ষিত লগইন",
    login_warn: "অননুমোদিত প্রবেশ আধার আইন, ২০১৬ এর অধীনে একটি শাস্তিযোগ্য অপরাধ।",
    role_admin: "কেন্দ্রীয় প্রশাসক",
    role_field: "মাঠ কর্মকর্তা",
    role_supervisor: "ডেটা সুপারভাইজার",
    sys_op: "সিস্টেম সচল",
    logout: "লগ আউট",
    dash_title: "জাতীয় ড্যাশবোর্ড",
    dash_subtitle: "সামাজিক ধরণ দেখতে একটি ডেটা স্তর নির্বাচন করুন",
    layer_enrolment: "তালিকাভুক্তি ঘনত্ব",
    layer_updates: "আপডেট কার্যকলাপ",
    layer_migration: "অভিবাসন সংকেত",
    layer_lifecycle: "জীবনচক্রের ব্যবধান",
    map_legend: "সূচক",
    map_high: "উচ্চ তীব্রতা",
    map_med: "মাঝারি",
    map_low: "কম / পদক্ষেপ প্রয়োজন",
    panel_pop: "মোট জনসংখ্যা",
    panel_sat: "তালিকাভুক্তি সম্পৃক্তি",
    panel_analysis: "সামাজিক বুদ্ধিমত্তা বিশ্লেষণ",
    panel_alerts: "সিস্টেম সতর্কতা",
    panel_rec: "সুপারিশকৃত শাসন ব্যবস্থা",
    panel_action_btn: "কর্ম পরিকল্পনা শুরু করুন",
    panel_data_as_of: "ডেটা আপডেট তারিখ",
    chart_trend: "৬-মাসের আপডেট প্রবণতা",
    chart_demog: "মুলতুবি জীবনচক্র আপডেট (বয়স অনুসারে)",
    fw_welcome: "স্বাগতম",
    fw_tasks: "অবশিষ্ট কাজ",
    fw_zone: "এলাকা",
    fw_new: "নতুন তালিকাভুক্তি",
    fw_verify: "স্থিতি যাচাই করুন",
    fw_assigned: "নির্ধারিত কাজ",
    fw_perf: "আমার ওয়ার্ড পারফরম্যান্স",
    fw_cov: "কভারেজ",
    fw_pending_05: "মুলতুবি ০-৫",
    fw_assisted: "সহায়তা",
    footer_rights: "ভারতের অনন্য পরিচয় কর্তৃপক্ষ। সর্বস্বত্ব সংরক্ষিত।",
    footer_privacy: "গোপনীয়তা নীতি",
    footer_terms: "পরিষেবার শর্তাবলী",
    footer_access: "অ্যাক্সেসযোগ্যতা",
    footer_disclaimer: "এই প্ল্যাটফর্মটি শুধুমাত্র বেনামী, সমষ্টিগত মেটাডেটা ব্যবহার করে।",

    dm_portal_title: "ডেটা ম্যানেজমেন্ট গেটওয়ে",
    dm_portal_subtitle: "তত্ত্বাবধানে ডেটাসেট ইনজেশন এবং পর্যবেক্ষণ",
    dm_login_link: "ডেটা ম্যানেজমেন্ট পোর্টালে যান",
    dm_main_link: "মূল পোর্টালে ফিরে যান",
    dm_total_records: "মোট রেকর্ড ইনজেস্টেড",
    dm_datasets: "আপলোড করা ডেটাসেট",
    dm_last_update: "শেষ ইনজেশন",
    dm_upload_title: "CSV ডেটাসেট ইনজেশন",
    dm_select_type: "ডেটাসেটের ধরন নির্বাচন করুন",
    dm_drop_file: "CSV ফাইল এখানে টেনে আনুন, অথবা ব্রাউজ করতে ক্লিক করুন",
    dm_uploading: "আপলোড এবং প্রসেসিং...",
    dm_upload_btn: "ডেটাসেট আপলোড করুন",
    dm_audit_log: "ইনজেশন অডিট লগ",
    dm_status_success: "সফল",
    dm_status_processing: "প্রক্রিয়াধীন",
    dm_status_failed: "ব্যর্থ",

    // Region Names
    region_india_avg: "ভারত (জাতীয় গড়)",
    region_mh: "মহারাষ্ট্র",
    region_up: "উত্তর প্রদেশ",
    region_kl: "কেরালা",
    region_gen: "অঞ্চল",

    // Region Names (Generic / All States)
    region_andhra_pradesh: "অন্ধ্র প্রদেশ",
    region_arunachal_pradesh: "অরুণাচল প্রদেশ",
    region_assam: "আসাম",
    region_bihar: "বিহার",
    region_chhattisgarh: "ছত্তিশগড়",
    region_goa: "গোয়া",
    region_gujarat: "গুজরাট",
    region_haryana: "হরিয়ানা",
    region_himachal_pradesh: "হিমাচল প্রদেশ",
    region_jammu_and_kashmir: "জম্মু ও কাশ্মীর",
    region_jharkhand: "ঝাড়খণ্ড",
    region_karnataka: "কর্ণাটক",
    region_kerala: "কেরালা",
    region_madhya_pradesh: "মধ্য প্রদেশ",
    region_maharashtra: "মহারাষ্ট্র",
    region_manipur: "মণিপুর",
    region_meghalaya: "মেঘালয়",
    region_mizoram: "মিজোরাম",
    region_nagaland: "নাগাল্যান্ড",
    region_odisha: "ওডিশা",
    region_punjab: "পাঞ্জাব",
    region_rajasthan: "রাজস্থান",
    region_sikkim: "সিকিম",
    region_tamil_nadu: "তামিলনাড়ু",
    region_telangana: "তেলেঙ্গানা",
    region_tripura: "ত্রিপুরা",
    region_uttar_pradesh: "উত্তর প্রদেশ",
    region_uttarakhand: "উত্তরাখণ্ড",
    region_west_bengal: "পশ্চিমবঙ্গ",
    
    // UTs and Variations
    region_andaman_and_nicobar_islands: "আন্দামান ও নিকোবর",
    region_andaman_and_nicobar: "আন্দামান ও নিকোবর",
    region_chandigarh: "চণ্ডীগড়",
    region_dadra_and_nagar_haveli_and_daman_and_diu: "দাদরা ও নগর হাভেলি",
    region_dadra_and_nagar_haveli: "দাদরা ও নগর হাভেলি",
    region_daman_and_diu: "দমন ও দিউ",
    region_delhi: "দিল্লি",
    region_nct_of_delhi: "দিল্লি",
    region_ladakh: "লাদাখ",
    region_lakshadweep: "লাক্ষাদ্বীপ",
    region_puducherry: "পুদুচেরি",

    // Data Content Keys
    alert_nat_1: "গ্রামীণ খাতে বাধ্যতামূলক বায়োমেট্রিক আপডেট পিছিয়ে আছে",
    rec_nat: "৫-১৫ বছর বয়সী গ্রুপের আপডেটের জন্য সচেতনতা প্রচার বাড়ান।",
    alert_mh_1: "পুणे/মুম্বাই করিডোরে উচ্চ অভিবাসন প্রবাহ সনাক্ত হয়েছে",
    alert_mh_2: "ঠিকানা আপডেট বৃদ্ধি",
    rec_mh: "অভিবাসন-নেতৃত্বাধীন ঠিকানা পরিবর্তনগুলি পরিচালনা করতে শিল্প অঞ্চলগুলিতে অতিরিক্ত আপডেট কিয়স্ক স্থাপন করুন।",
    alert_up_1: "নেপাল সীমান্তবর্তী জেলাগুলিতে কম সম্পৃক্তি",
    alert_up_2: "০-৫ তালিকাভুক্তি ব্যবধান",
    rec_up: "নবজাতক এবং শিশুদের জন্য অঙ্গনওয়াড়ি স্তরে তালিকাভুক্তি ক্যাম্প শুরু করুন।",
    alert_kl_1: "বয়স্ক জনসংখ্যা বায়োমেট্রিক অমিল বাড়ছে",
    rec_kl: "বয়স্ক জনসংখ্যার জন্য সহায়তাপ্রাপ্ত হোম-ভিজিট আপডেটের উপর ফোকাস করুন।",
    alert_gen: "রুটিন মনিটরিং সক্রিয়",
    alert_gen_min: "ছোট অসঙ্গতি সনাক্ত হয়েছে",
    rec_gen: "বর্তমান পরিষেবার স্তর বজায় রাখুন।",
    rec_gen_mob: "মোবাইল আপডেট ইউনিট স্থাপনের সুপারিশ করা হয়েছে।",

    // Insight Narrative Keys
    insight_mig_influx: "অভিবাসন ডেটা জনসংখ্যার নিট আগমন নির্দেশ করে। ঠিকানা আপডেটের ধরণগুলি নির্দেশ করে যে চলাচল মূলত শিল্প শ্রমের চাহিদার দ্বারা চালিত হয়।",
    insight_mig_outflow: "অভিবাসন ডেটা জনসংখ্যার নিট বহির্গমন নির্দেশ করে। ঠিকানা আপডেটের ধরণগুলি নির্দেশ করে যে চলাচল মূলত মৌসুমী কৃষি পরিবর্তনের দ্বারা চালিত হয়।",
    insight_life_lag: "বাধ্যতামূলক বায়োমেট্রিক আপডেটগুলি গুরুতরভাবে পিছিয়ে আছে। ৫-১৫ বছর বয়সী জনসংখ্যার মধ্যে তাৎক্ষণিক বায়োমেট্রিক রিফ্রেশ প্রয়োজন এমন একটি উল্লেখযোগ্য ব্যবধান রয়েছে।",
    insight_life_stable: "বাধ্যতামূলক বায়োমেট্রিক আপডেটগুলি স্থিতিশীল। ৫-১৫ বছর বয়সী জনসংখ্যার মধ্যে তাৎক্ষণিক বায়োমেট্রিক রিফ্রেশ প্রয়োজন এমন একটি উল্লেখযোগ্য ব্যবধান রয়েছে।",
    insight_activity_high: "আঞ্চলিক কার্যকলাপ আধার পরিষেবাগুলির সাথে উচ্চ সম্পৃক্ততা দেখায়। জনসংখ্যার কভারেজ অনুমানগুলি প্রজেক্টেড আদমশুমারি ডেটার সাথে সামঞ্জস্যপূর্ণ।",
    insight_activity_mod: "আঞ্চলিক কার্যকলাপ আধার পরিষেবাগুলির সাথে মাঝারি সম্পৃক্ততা দেখায়। জনসংখ্যার কভারেজ অনুমানগুলি প্রজেক্টেড আদমশুমারি ডেটার সাথে সামঞ্জস্যপূর্ণ."
  },
  mr: {
    app_title: "ASIAGS",
    app_subtitle: "आधार सामाजिक बुद्धिमत्ता आणि अनुकूलनशील शासन प्रणाली",
    gov_india: "भारत सरकार",
    satyameva: "सत्यमेव जयते",
    login_auth: "केवळ अधिकृत कर्मचारी",
    login_userid: "वापरकर्ता आयडी",
    login_password: "पासवर्ड",
    login_btn: "सुरक्षित लॉगिन",
    login_warn: "अनधिकृत प्रवेश आधार कायदा, २०१६ अंतर्गत दंडनीय गुन्हा आहे.",
    role_admin: "केंद्रीय प्रशासक",
    role_field: "क्षेत्र अधिकारी",
    role_supervisor: "डेटा पर्यवेक्षक",
    sys_op: "प्रणाली चालू आहे",
    logout: "लॉग आउट",
    dash_title: "राष्ट्रीय डॅशबोर्ड",
    dash_subtitle: "सामाजिक नमुने पाहण्यासाठी डेटा स्तर निवडा",
    layer_enrolment: "नावनोंदणी घनता",
    layer_updates: "अद्यतन क्रियाकलाप",
    layer_migration: "स्थलांतर संकेत",
    layer_lifecycle: "जीवनचक्र अंतर",
    map_legend: "सूची",
    map_high: "उच्च तीव्रता",
    map_med: "मध्यम",
    map_low: "कमी / कृती आवश्यक",
    panel_pop: "एकूण लोकसंख्या",
    panel_sat: "नावनोंदणी संपृक्तता",
    panel_analysis: "सामाजिक बुद्धिमत्ता विश्लेषण",
    panel_alerts: "सिस्टम अलर्ट",
    panel_rec: "शिफारस केलेली शासन कृती",
    panel_action_btn: "कृती योजना सुरू करा",
    panel_data_as_of: "डेटा अद्यतन दिनांक",
    chart_trend: "६-महिन्यांचा अद्यतन कल",
    chart_demog: "प्रलंबित जीवनचक्र अद्यतने (वयानुसार)",
    fw_welcome: "स्वागत आहे",
    fw_tasks: "उर्वरित कार्ये",
    fw_zone: "विभाग",
    fw_new: "नवीन नावनोंदणी",
    fw_verify: "स्थिती तपासा",
    fw_assigned: "नेमून दिलेली कार्ये",
    fw_perf: "माझी प्रभाग कामगिरी",
    fw_cov: "कव्हरेज",
    fw_pending_05: "प्रलंबित ०-५",
    fw_assisted: "सहाय्यित",
    footer_rights: "भारतीय विशिष्ट ओळख प्राधिकरण. सर्व हक्क राखीव.",
    footer_privacy: "गोपनीयता धोरण",
    footer_terms: "सेवा अटी",
    footer_access: "सुलभता",
    footer_disclaimer: "हे व्यासपीठ केवळ निनावी, एकत्रित मेटाडेटा वापरते.",

    dm_portal_title: "डेटा व्यवस्थापन गेटवे",
    dm_portal_subtitle: "पर्यवेक्षित डेटासेट अंतर्ग्रहण आणि देखरेख",
    dm_login_link: "डेटा व्यवस्थापन पोर्टलवर स्विच करा",
    dm_main_link: "मुख्य पोर्टलवर परत जा",
    dm_total_records: "एकूण रेकॉर्ड्स अंतर्ग्रहण",
    dm_datasets: "अपलोड केलेले डेटासेट",
    dm_last_update: "अंतिम अंतर्ग्रहण",
    dm_upload_title: "CSV डेटासेट अंतर्ग्रहण",
    dm_select_type: "डेटासेट प्रकार निवडा",
    dm_drop_file: "CSV फाईल येथे ड्रॅग आणि ड्रॉप करा, किंवा ब्राउझ करण्यासाठी क्लिक करा",
    dm_uploading: "अपलोड आणि प्रक्रिया...",
    dm_upload_btn: "डेटासेट अपलोड करा",
    dm_audit_log: "अंतर्ग्रहण ऑडिट लॉग",
    dm_status_success: "यशस्वी",
    dm_status_processing: "प्रक्रिया चालू",
    dm_status_failed: "अयशस्वी",

    // Region Names
    region_india_avg: "भारत (राष्ट्रीय सरासरी)",
    region_mh: "महाराष्ट्र",
    region_up: "उत्तर प्रदेश",
    region_kl: "केरळ",
    region_gen: "प्रदेश",

    // Region Names (Generic / All States)
    region_andhra_pradesh: "आंध्र प्रदेश",
    region_arunachal_pradesh: "अरुणाचल प्रदेश",
    region_assam: "आसाम",
    region_bihar: "बिहार",
    region_chhattisgarh: "छत्तीसगड",
    region_goa: "गोवा",
    region_gujarat: "गुजरात",
    region_haryana: "हरियाणा",
    region_himachal_pradesh: "हिमाचल प्रदेश",
    region_jammu_and_kashmir: "जम्मू आणि काश्मीर",
    region_jharkhand: "झारखंड",
    region_karnataka: "कर्नाटक",
    region_kerala: "केरळ",
    region_madhya_pradesh: "मध्य प्रदेश",
    region_maharashtra: "महाराष्ट्र",
    region_manipur: "मणिपूर",
    region_meghalaya: "मेघालय",
    region_mizoram: "मिझोरम",
    region_nagaland: "नागालँड",
    region_odisha: "ओडिशा",
    region_punjab: "पंजाब",
    region_rajasthan: "राजस्थान",
    region_sikkim: "सिक्कीम",
    region_tamil_nadu: "तमिळनाडू",
    region_telangana: "तेलंगणा",
    region_tripura: "त्रिपुरा",
    region_uttar_pradesh: "उत्तर प्रदेश",
    region_uttarakhand: "उत्तराखंड",
    region_west_bengal: "पश्चिम बंगाल",
    
    // UTs and Variations
    region_andaman_and_nicobar_islands: "अंदमान आणि निकोबार",
    region_andaman_and_nicobar: "अंदमान आणि निकोबार",
    region_chandigarh: "चंदिगढ",
    region_dadra_and_nagar_haveli_and_daman_and_diu: "दादरा आणि नगर हवेली",
    region_dadra_and_nagar_haveli: "दादरा आणि नगर हवेली",
    region_daman_and_diu: "दमण आणि दीव",
    region_delhi: "दिल्ली",
    region_nct_of_delhi: "दिल्ली",
    region_ladakh: "लडाख",
    region_lakshadweep: "लक्षद्वीप",
    region_puducherry: "पुडुचेरी",

    // Data Content Keys
    alert_nat_1: "ग्रामीण भागात अनिवार्य बायोमेट्रिक अद्यतने मागे आहेत",
    rec_nat: "५-१५ वर्षे वयोगटातील अद्यतनांसाठी जागरूकता मोहीम वाढवा.",
    alert_mh_1: "पुणे/मुंबई कॉरिडॉरमध्ये उच्च स्थलांतर ओघ आढळला",
    alert_mh_2: "पत्ता अद्यतनात वाढ",
    rec_mh: "स्थलांतरित पत्ता बदल हाताळण्यासाठी औद्योगिक झोनमध्ये अतिरिक्त अद्यतन किओस्क तैनात करा.",
    alert_up_1: "नेपाळच्या सीमेला लागून असलेल्या जिल्ह्यांमध्ये कमी संपृक्तता",
    alert_up_2: "०-५ नावनोंदणी अंतर",
    rec_up: "नवजात आणि बालकांसाठी अंगणवाडी स्तरावर नावनोंदणी शिबिरे सुरू करा.",
    alert_kl_1: "वृद्ध लोकसंख्येमध्ये बायोमेट्रिक तफावत वाढत आहे",
    rec_kl: "वृद्ध लोकांसाठी घरी जाऊन अद्यतन करण्यावर लक्ष केंद्रित करा.",
    alert_gen: "नियमित देखरेख सक्रिय",
    alert_gen_min: "किरकोळ त्रुटी आढळल्या",
    rec_gen: "सध्याची सेवा पातळी कायम ठेवा.",
    rec_gen_mob: "मोबाईल अपडेट युनિટ्स तैनात करण्याची शिफारस.",

    // Insight Narrative Keys
    insight_mig_influx: "स्थलांतर डेटा लोकसंख्येचा निव्वळ ओघ दर्शवतो. पत्ता अद्यतन नमुने सूचित करतात की हालचाल प्रामुख्याने औद्योगिक कामगार मागणीमुळे होते.",
    insight_mig_outflow: "स्थलांतर डेटा लोकसंख्येचा निव्वळ बाह्यप्रवाह दर्शवतो. पत्ता अद्यतन नमुने सूचित करतात की हालचाल प्रामुख्याने हंगामी कृषी बदलांमुळे होते.",
    insight_life_lag: "अनिवार्य बायोमेट्रिक अद्यतने गंभीरपणे मागे आहेत. ५-१५ वर्षे वयोगटात त्वरित बायोमेट्रिक रिफ्रेश आवश्यक असलेली महत्त्वपूर्ण तफावत आहे.",
    insight_life_stable: "अनिवार्य बायोमेट्रिक अद्यतने स्थिर आहेत. ५-१५ वर्षे वयोगटात त्वरित बायोमेट्रिक रिफ्रेश आवश्यक असलेली महत्त्वपूर्ण तफावत आहे.",
    insight_activity_high: "प्रादेशिक क्रियाकलाप आधार सेवांसह उच्च सहभाग दर्शवितात. लोकसंख्या कव्हरेज अंदाज अंदाजित जनगणनेच्या डेटाशी जुळतात.",
    insight_activity_mod: "प्रादेशिक क्रियाकलाप आधार सेवांसह मध्यम सहभाग दर्शवितात. लोकसंख्या कव्हरेज अंदाज अंदाजित जनगणनेच्या डेटाशी जुळतात."
  }
};